name: cuzdan
description: Cameloott Wallet Application Project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.0
  flutter:
    sdk: flutter
  mobx: ^2.0.6+1
  provider: ^6.0.2
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/languages/
